### ISSUE TITLE
Autosave triggers on unsavable files

### ISSUE THREAD

**Issue by daniocean** [atom/autosave#17]
Hi guys.

Some plugins like "atom-coffeescript-preview" are opening a separate tab where a compiled version of the code is visible(CS to JS). The file is a temporary file that doesn't have the `getModel()` method and therefore causes exception.

A possible fix is to check for the method existence before calling it, although I would suggest actually looking into other alternatives.

This:
```coffeescript
    activate: ->
        atom.workspaceView.on 'focusout', ".editor:not(.mini)", (event) =>
          editor = $(event.target).closest('.editor').view()?.getModel()
          @autosave(editor)
```

should be:
```coffeescript
    activate: ->
        atom.workspaceView.on 'focusout', ".editor:not(.mini)", (event) =>
          editor = $(event.target).closest('.editor').view()?.getModel?()
          @autosave(editor)
```

**Comment by kevinsawicki** [comment]
I don't think this should happen anymore with the latest autosave package. If only saves items that provide a path and that path exists on disk and items that implement `isModified` as well.

Please comment if you still see this happening on Atom 1.0.3+
