### ISSUE TITLE
autosaving deleted, moved, renamed files

### ISSUE THREAD

**Issue by nruth** [atom/autosave#30]
Bug: any open file that gets renamed or deleted will be ressurected by autosave.

This is a usability nightmare. Often results in editing the wrong file, or files that should have been deleted not getting deleted.

**Comment by balexand** [comment]
This is a duplicate of #9. And there's a fix in #35.

**Comment by lee-dohm** [comment]
Thanks @balexand. It is a duplicate. People interested in this should subscribe there for updates.
