### ISSUE TITLE
When is auto-saving happening?

### ISSUE THREAD

**Issue by mkorfmann** [atom/autosave#42]
When are files actually auto-saved? Plugin is enabled for my installation but I keep running into occasions where I forget to save and find myself searching a non-existent bug for a few minutes...

(Would really love this to work like Rubymine auto-saving, never had any issues with that)

**Comment by kevinsawicki** [comment]
All open editors are autosaved whenever the window loses focus or the window is closed.

The active editor is autosaved whenever it loses focus such as when switching tabs.

You might want to make sure you have have the "Enabled" box check under the autosave package's settings in the Settings view to make sure the package is autosaving, hope this helps.
