### ISSUE TITLE
Can autosave be turned off per grammer or by some selector?

### ISSUE THREAD

**Issue by jsg2021** [atom/autosave#43]
I use git plus and the autosave makes the commit editor close before I'm done. (I cross ref things alot and the editor loses focus)

akonwi/git-plus#235

**Comment by jsg2021** [comment]
This comment inspired this question:
https://github.com/akonwi/git-plus/issues/235#issuecomment-122347841

**Comment by rsese** [comment]
We found a few duplicates asking for this enhancement, closing in favor of https://github.com/atom/autosave/issues/64 since it's mentions a community package that potentially provides this behavior.
