### ISSUE TITLE
My autosave no longer works

### ISSUE THREAD

**Issue by wardch** [atom/autosave#48]
Yesterday while coding I accidentally hit some combination of keys, which quitted me out of Atom and then when I reopened it autosave no longer worked. I have to know manually hit command-s every time I want to save something. 

I downloaded another autosave package but it still won't work. Do you know why the original autosave will no longer work for me?

**Comment by 50Wliu** [comment]
You're probably hitting atom/atom#8849 where the file isn't getting detected as modified.

**Comment by 50Wliu** [comment]
Should be fixed in Atom 1.0.18.
