### ISSUE TITLE
Add scope-specific autosave setting

### ISSUE THREAD

**Issue by jronallo** [atom/autosave#53]
If autosave is enabled in the main config it works in Atom 1.2.0, but if I try to turn autosave on for only one language it does not work. I believe in Atom 1.1.0 it was working. I have the following config.

``` coffeescript
"source.gfm":
  editor:
    softWrap: true
  autosave:
    enabled: true
```

**Comment by lee-dohm** [comment]
Atom v1.1.0 and all versions since have been using v0.23.0 of this package. So there couldn't have been a change between v1.1.0 and v1.2.0. Also, looking at the history of the package ... I don't see any support for scope-specific configuration.

**Comment by rsese** [comment]
We found a few duplicates asking for this enhancement, closing in favor of https://github.com/atom/autosave/issues/64 since it's mentions a community package that potentially provides this behavior.
