### ISSUE TITLE
Unable to recover untitled temporary file when Atom crash

### ISSUE THREAD

**Issue by tribbloid** [atom/autosave#72]
Currently the untitled file are stored in encoded json temporary file, it is very hard to recover with a third party tool when atom crashed.

I would suggest to give the option to always save as real text file without encoding, and add the untitled file into 'recently opened' list, so nothing will be lost in case of a crash.

**Comment by 50Wliu** [comment]
Please open a new issue and **completely** fill out the provided issue template.  Thanks!
