### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by simoxi** [atom/autosave#79]
You have the core package "autosave" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (C:\Users\Wang\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\dalek\lib\main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (C:\Users\Wang\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
Emitter.emit (C:\Users\Wang\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:141:28)
<unknown> (C:\Users\Wang\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:514:32)
```

**Comment by Ben3eeE** [comment]
You have the core package "autosave" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
