### ISSUE TITLE
data loss with new C++ text buffer backend under some cirumstances

### ISSUE THREAD

**Issue by despairblue** [atom/autosave#80]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since Atom 1.19 enabling this plugin can lead to data loss.

### Steps to Reproduce

1. Enable autosave.
2. Open a file.
3. Enter `test` enter.
4. Save.
5. Remove new line.
6. Hit `cmd-w`.

**Expected behavior:** [What you expect to happen]

File should either be saved or atom should ask if you want to save the changes to the file.

**Actual behavior:** [What actually happens]

Empty file is saved.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Evertime for removing new lines, happens in conjunction with prettier-atom in all cases where prettier changes the file. See: https://github.com/prettier/prettier-atom/issues/264

### Versions

* **Atom:**       1.19.7
* **Atom-Shell:** 
* **OS:**         Mac OS X 10.12.6
* **Misc**
    * apm  1.18.4
    * npm  3.10.10
    * node 6.9.5 x64
    * python 2.7.10
    * git 2.11.0

### Additional Information

![autosave](https://user-images.githubusercontent.com/927609/30332721-5cace334-97db-11e7-880d-f50416e85165.gif)

**Comment by despairblue** [comment]
Disabling the `whitespace` package prevents this from happening. So I guess this happens whenever a package changes the buffer `onWillSave`.

Yep, just checked, also happens when using `editorconfig` instead of `whitespace`.

**Comment by despairblue** [comment]
@Ben3eeE I'm happy to help reproduce this, I tested this with `atom --safe` and `whitespace` and `autosave` plugins enabled. It always saved an empty file when removing the trailing new line or adding a trailing whitespace to a line.

**Comment by maxbrunsfeld** [comment]
Wow thanks for the report and I apologize for this very serious regression. I'll be working on this today.

**Comment by despairblue** [comment]
Thanks for working on this, luckily I lost nothing major, just refactoring grunt work 😄

**Comment by maxbrunsfeld** [comment]
@despairblue I haven't been able to reproduce this yet; at the final step, when I type `cmd-w`, I am prompted to save the file as expected. If instead of using `cmd-w` I focus another window, Atom saves the correct contents of the file.

Does this happen if you run atom in safe mode?

**Comment by maxbrunsfeld** [comment]
Oh, nevermind. I had the `Ensure Single Trailing Newline` option turned off. With that option enabled, I can reproduce this using your steps.

**Comment by despairblue** [comment]
@maxbrunsfeld Thank you ❤️
