### ISSUE TITLE
Autosave 0.24.6 throws stack trace on focus change when enabled.

### ISSUE THREAD

**Issue by michael-gracy** [atom/autosave#86]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
     

> Not reproducible in safe mode. 

    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Throws stack trace upon changing focus away from tab:
internal/process/warning.js:21 (node:92052) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
process.on @ internal/process/warning.js:21
emitOne @ events.js:96
emit @ events.js:188
process.nextTick @ internal/process/warning.js:47
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
logger.coffee [sm]:61 2/21/2018 2:17:35 PM - beautifiers/index.coffee [error]:  Error: connect ECONNREFUSED 127.0.0.1:36805
    at Object.exports._errnoException (util.js:1022)
    at exports._exceptionWithHostPort (util.js:1045)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090)
internal/process/warning.js:21 (node:92052) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
process.on @ internal/process/warning.js:21
emitOne @ events.js:96
emit @ events.js:188
process.nextTick @ internal/process/warning.js:47
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

Disabling Autosave removes error. Error doesn't occur in safe mode.
The provided stack trace, above, is all that shows up in the dev console.

### Steps to Reproduce

1. [First Step] Enable AutoSave
2. [Second Step] make any change to a file and change tabs

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens] File is saved.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Versions
atom --version; apm --version
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.10
git 2.16.2
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information
Disabling it makes it go away. This hasn't been working now for sometime.

Any additional information, configuration or data that might be necessary to reproduce the issue.
apm list:
Built-in Atom Packages (92)
├── atom-dark-syntax@0.29.0
├── atom-dark-ui@0.53.1
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.1
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.9
├── one-light-ui@1.10.9
├── one-dark-syntax@1.8.1
├── one-light-syntax@1.8.1
├── solarized-dark-syntax@1.1.3
├── solarized-light-syntax@1.1.3
├── about@1.7.8
├── archive-view@0.64.1
├── autocomplete-atom-api@0.10.6
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.4
├── autocomplete-plus@2.40.0
├── autocomplete-snippets@1.11.2
├── autoflow@0.29.0
├── autosave@0.24.6
├── background-tips@0.27.1 (disabled)
├── bookmarks@0.45.0
├── bracket-matcher@0.88.1
├── command-palette@0.43.3
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.7
├── exception-reporting@0.42.0
├── find-and-replace@0.215.0
├── fuzzy-finder@1.7.3
├── github@0.8.3
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.8
├── image-view@0.62.4
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.1
├── line-ending-selector@0.7.4
├── link@0.31.4
├── markdown-preview@0.159.20
├── metrics@1.2.6 (disabled)
├── notifications@0.70.2
├── open-on-github@1.3.1
├── package-generator@1.3.0
├── settings-view@0.253.1-0
├── snippets@1.1.9
├── spell-check@0.72.5 (disabled)
├── status-bar@1.8.15
├── styleguide@0.49.9
├── symbols-view@0.118.1
├── tabs@0.109.1
├── timecop@0.36.2
├── tree-view@0.221.3
├── update-package-dependencies@0.13.0
├── welcome@0.36.6
├── whitespace@0.37.5
├── wrap-guide@0.40.3
├── language-c@0.58.1
├── language-clojure@0.22.5
├── language-coffee-script@0.49.3
├── language-csharp@0.14.3
├── language-css@0.42.8
├── language-gfm@0.90.3 (disabled)
├── language-git@0.19.1
├── language-go@0.44.4 (disabled)
├── language-html@0.48.5
├── language-hyperlink@0.16.3
├── language-java@0.27.6
├── language-javascript@0.127.7
├── language-json@0.19.1
├── language-less@0.34.1
├── language-make@0.22.3
├── language-mustache@0.14.4
├── language-objective-c@0.15.1
├── language-perl@0.38.1
├── language-php@0.43.0
├── language-property-list@0.9.1
├── language-python@0.45.6 (disabled)
├── language-ruby@0.71.4
├── language-ruby-on-rails@0.25.3
├── language-sass@0.61.3
├── language-shellscript@0.25.4
├── language-source@0.9.0
├── language-sql@0.25.9
├── language-text@0.7.3
├── language-todo@0.29.3
├── language-toml@0.18.1
├── language-typescript@0.2.3 (disabled)
├── language-xml@0.35.2
└── language-yaml@0.31.1

Community Packages (76) /Users/michael.gracy/.atom/packages
├── Sublime-Style-Column-Selection@1.7.4
├── atom-autocomplete-php@0.25.6 (disabled)
├── atom-beautify@0.30.9
├── atom-ide-ui@0.9.1
├── atom-json-editor@0.4.1
├── atom-package-sync@0.2.6
├── atom-shell-commands@1.5.0
├── atom-typescript@12.1.2
├── autocomplete-ansible@0.1.15
├── autocomplete-bash-builtins@0.3.5
├── autocomplete-json@5.5.2
├── autocomplete-python@1.10.5 (disabled)
├── background-tips@0.28.0 (disabled)
├── busy-signal@1.4.3
├── code-annotations@2.1.3 (disabled)
├── dash@1.7.1
├── dash-on-cursor-active@0.1.2
├── file-icons@2.1.16
├── file-types@0.5.5
├── fold-lines@0.2.2
├── git-blame@1.5.0
├── git-diff-details@1.4.0
├── git-plus@7.10.0
├── git-time-machine@1.5.9
├── go-debug@1.6.0 (disabled)
├── go-plus@5.8.2 (disabled)
├── go-signature-statusbar@1.2.3 (disabled)
├── gotests@0.3.0 (disabled)
├── hyperclick@0.1.5 (disabled)
├── ide-go@0.6.1 (disabled)
├── ide-json@0.2.1
├── ide-python@0.8.0 (disabled)
├── intentions@1.1.5
├── json-colorer@1.0.0
├── json-generator@0.1.15
├── jsonlint@1.1.4
├── language-ansible@0.2.2
├── language-gfm@0.90.3 (disabled)
├── language-go@0.45.2 (disabled)
├── language-markdown@0.25.1
├── language-powershell@4.0.0 (disabled)
├── language-puppet@0.23.0
├── language-typescript@0.3.2 (disabled)
├── linter@2.2.0 (disabled)
├── linter-ansible-linting@1.3.1 (disabled)
├── linter-checkbashisms@0.1.5 (disabled)
├── linter-markdown@5.2.0
├── linter-puppet-lint@0.8.4 (disabled)
├── linter-python@3.1.2 (disabled)
├── linter-python-pep8@0.2.0 (disabled)
├── linter-shellcheck@1.4.6
├── linter-ui-default@1.6.10
├── lipsum@0.1.0
├── markdown-pdf@2.1.0
├── markdown-preview-plus@2.5.3 (disabled)
├── markdown-scroll-sync@2.1.2
├── markdown-writer@2.7.3
├── metrics@1.2.6 (disabled)
├── overlay-status-icons@0.1.6
├── project-manager@3.3.5
├── python-debugger@0.2.0 (disabled)
├── python-indent@1.1.4 (disabled)
├── python-nosetests@0.2.0 (disabled)
├── python-tools@0.6.9 (disabled)
├── qolor@0.4.2
├── save-session@0.15.7
├── script@3.17.3
├── spell-check@0.72.7 (disabled)
├── ssh-config@0.13.0 (disabled)
├── svn@0.0.13
├── termination@0.6.1
├── todo-show@2.2.0
├── tool-bar@1.1.6
├── tool-bar-atom@1.7.0
├── tool-bar-config@0.1.0
└── zentabs@0.8.9

**Comment by 50Wliu** [comment]
> logger.coffee [sm]:61 2/21/2018 2:17:35 PM - beautifiers/index.coffee [error]: Error: connect ECONNREFUSED 127.0.0.1:36805

Looks like a problem with one of your beautifier packages.  You can try using the [package-cop](https://atom.io/packages/package-cop) package to identify which package is causing the issue.
